### ISSUE TITLE
Local users cannot work, if T3AM-Server is not available

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/t3am#1]
If the team server is not available to a client instance, even local users cannot work any more.

There should be a time-out if the instance is not available . Other solution could be to "ping" the server (similar how EXT:solr checks the availability of the solr server )

**Comment by sbusemann** [comment]
https://projekte.in2code.de/issues/30726

**Comment by mschwemer** [comment]
I cannot reproduce this any more ...
