### ISSUE TITLE
[TASK] TYPO3 v11 compatibility

### ISSUE THREAD

**Issue by BastianBalthasarBux** [in2code-de/t3am#14]
Is it already compatible with TYPO3 v11 LTS? If so, version information should get updated.

**Comment by sbusemann** [comment]
Dear @BastianBalthasarBux -> we replaced internally T3AM with a gitlab authenticator. So at the moment we are not working on v11 compatibilty. But we will try to merge the pull request.

**Comment by BastianBalthasarBux** [comment]
What are the further plans? Will the whole thing die a silent death then?

**Comment by sbusemann** [comment]
We will not do a further active development. We will merge pull requests and are willing to add contributors or hand over responsibility

**Comment by BastianBalthasarBux** [comment]
:sob:

**Comment by sbusemann** [comment]
released
